### ISSUE TITLE
self.is_in(BCD, 1.13, 1.168), the fib ratio is wrong

### ISSUE THREAD

**Issue by howie1013** [djoffrey/HarmonicPatterns#2]
self.is_in(BCD, 1.13, 1.168), the fib ratio is wrong

**Comment by ojashyadav101** [comment]
> 

What should it be?

**Comment by djoffrey** [comment]
Hi, @howie1013 ,
According to the reference, for example, gartley pattern:

[https://harmonicpattern.com/blog/gartley-pattern/](https://harmonicpattern.com/blog/gartley-pattern/)

1.13 to 1.618 is the range, did I misunderstand this?

**Comment by djoffrey** [comment]
Outdated
