### ISSUE TITLE
from HarmonicPatterns.harmonic import send_alert, search_function

### ISSUE THREAD

**Issue by shahkaran76** [djoffrey/HarmonicPatterns#3]
from HarmonicPatterns.harmonic import send_alert, search_function

This example code does not work as harmonic.py file does not exist. Please suggest

**Comment by djoffrey** [comment]
sorry, the code is too old.

function send_alert and search_function could be found in example/run_detect.py 

I think the working part left is:

ccxt fetch_kline -> HarmonicDetector search() -> output

**Comment by djoffrey** [comment]
sorry, the code is too old.

function send_alert and search_function could be found in example/run_detect.py 

I think the working part left is:

ccxt fetch_kline -> HarmonicDetector search() -> output

**Comment by ozturkeyupp54** [comment]
hello as far as I understand it gives the following error when running "search_function":

NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo

I tried to understand how it followed to draw information from the ccxt library, but it didn't. can you help?

By the way, I get this error when I run the DETECT BTC cell in the "HarmoCurrent.ipynb" file, the code is below:

s = ['BTC/USDT', 'ETH/USDT']
search('binance', s, periods = ['15m', '30m', '1h', '4h'])

**Comment by djoffrey** [comment]
> 

please refer to the updated notebook, with a step by step. Should be easy to try
