### ISSUE TITLE
NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo

### ISSUE THREAD

**Issue by PardeepRassani** [djoffrey/HarmonicPatterns#6]
Hello,
It gives the following error when running following code:

binance = getattr(ccxt, 'binance')(ccxt_options)
markerts = binance.load_markets()
symbol = 'BTC/USDT'
period = '4h'

ProxyError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcdac308490>: Failed to establish a new connection: [Errno 111] Connection refused')))

Can you please help with this?

**Comment by boydtech761** [comment]
Message https://t.me/boydtech on telegram he’s the best on account recovering

**Comment by djoffrey** [comment]
Just remove the proxy in the ccxt_options
