### ISSUE TITLE
Cant add timestamp on my points that form a pattern

### ISSUE THREAD

**Issue by cunhasdepedra** [djoffrey/HarmonicPatterns#8]
@djoffrey can you help me out? I think discord would be better. But here it is: 

def fetch_usdt_pairs():
    exclude_symbols = ["SRMUSDT", "HNTUSDT", "CVCUSDT", "BTSUSDT", "BTCSTUSDT", "SCUSDT", "TLMUSDT", "RAYUSDT", "FTTUSDT", "1000SHIBUSDT",  "BTCDOMUSDT", "1000LUNCUSDT", "BLUEBIRDUSDT", "1000XECUSDT", "FOOTBALLUSDT", "ETHUSDT_230630", "LUNA2USDT", "DEFIUSDT"]
    futures_pairs = client.futures_exchange_info()["symbols"]
    return [pair["symbol"] for pair in futures_pairs if pair["quoteAsset"] == "USDT" and pair["symbol"] not in exclude_symbols]

def fetch_historical_data(symbol, interval, limit=500, start_time=None, end_time=None):
    try:
        klines = client.get_klines(symbol=symbol, interval=interval, limit=limit, startTime=start_time, endTime=end_time)
        data = pd.DataFrame(klines, columns=["open_time", "open", "high", "low", "close", "volume", "close_time", "quote_asset_volume", "number_of_trades", "taker_buy_base_asset_volume", "taker_buy_quote_asset_volume", "ignore"])
        data = data.astype({"open": "float64", "high": "float64", "low": "float64", "close": "float64"})
        return data
    except BinanceAPIException as e:
        print(f"Error fetching historical data for {symbol}: {e}")
        return pd.DataFrame()
    
def analyze_patterns(interval):
    usdt_pairs = fetch_usdt_pairs()

    bullish_patterns = []
    bearish_patterns = []

    for symbol in usdt_pairs:
        data = fetch_historical_data(symbol, interval)
        if not data.empty:
            if data.shape[0] < 500:
                print(f"Symbol: {symbol}")
                print("Insufficient data\n")

            harmonic_detector = HarmonicDetector()
            patterns, _ = harmonic_detector.search_patterns(data)  # Extract only the found patterns list
            if len(patterns) > 0:
                latest_pattern = patterns[-1]
                if "bullish" in latest_pattern[2]:
                    bullish_patterns.append((symbol, latest_pattern))
                elif "bearish" in latest_pattern[2]:
                    bearish_patterns.append((symbol, latest_pattern))
        else:
            print(f"Symbol: {symbol}")
            print("No data available\n")

        time.sleep(1)  # Add sleep to avoid hitting rate limits

    print(f"\nInterval: {interval}")

    # Print bullish patterns
    print(f"Bullish patterns:")
    for symbol, pattern in bullish_patterns:
        print(f"Symbol: {symbol}")
        print(f"Pattern: {pattern[2]}")
        print("Prices:", [point[1] for point in pattern[0]])
        print("\n")

    print("\n")

    # Print bearish patterns
    print(f"Bearish patterns:")
    for symbol, pattern in bearish_patterns:
        print(f"Symbol: {symbol}")
        print(f"Pattern: {pattern[2]}")
        print("Prices:", [point[1] for point in pattern[0]])
        print("\n")

if __name__ == "__main__":
    intervals = [
        Client.KLINE_INTERVAL_2HOUR,
        Client.KLINE_INTERVAL_4HOUR,
        Client.KLINE_INTERVAL_12HOUR,
        Client.KLINE_INTERVAL_1DAY,
        Client.KLINE_INTERVAL_3DAY,
    ]

    for interval in intervals:
        analyze_patterns(interval)

I get the price and the timeframe, but every time I try to add timestamp I get lots of errors. Timestamp for each point of the pattern is very important, otherwise I'll get lost. Cant validate etc. I have all the functions built in this example here inside my code: https://github.com/djoffrey/HarmonicPatterns/blob/main/src/harmonic_patterns.py

Please help.

**Comment by djoffrey** [comment]
I don't see your error messages, but you could change this function to keep the timestamp axis:
```
def kline_to_df(arr) -> pd.DataFrame:
    kline = pd.DataFrame(
        arr,
        columns=['ts', 'open', 'high', 'low', 'close', 'volume' ])
    kline.index = pd.to_datetime(kline.ts, unit='ms')
    kline.drop('ts', axis=1, inplace=True) # -> remove this line will keep
    return kline
```

**Comment by cunhasdepedra** [comment]
Thanks a lot!

What about here? 

def fetch_historical_data(symbol, interval, min_required=500, start_time=None, end_time=None):
    try:
        klines = client.get_klines(symbol=symbol, interval=interval, limit=min_required, startTime=start_time, endTime=end_time)
        data = pd.DataFrame(klines, columns=["open_time", "open", "high", "low", "close", "volume", "close_time", "quote_asset_volume", "number_of_trades", "taker_buy_base_asset_volume", "taker_buy_quote_asset_volume", "ignore"])
        data = data.astype({"open": "float64", "high": "float64", "low": "float64", "close": "float64"})
        
        if data.shape[0] < min_required:
            klines = client.get_klines(symbol=symbol, interval=interval, startTime=start_time, endTime=end_time)
            data = pd.DataFrame(klines, columns=["open_time", "open", "high", "low", "close", "volume", "close_time", "quote_asset_volume", "number_of_trades", "taker_buy_base_asset_volume", "taker_buy_quote_asset_volume", "ignore"])
            data = data.astype({"open": "float64", "high": "float64", "low": "float64", "close": "float64"})

        # Convert 'open_time' to datetime and set it as the index
        data['open_time'] = pd.to_datetime(data['open_time'], unit='ms')
        data.set_index('open_time', inplace=True)
        
        Will I have problem with this too? My error is that typical integer, boolean etc. stuff: https://www.positioniseverything.net/arrays-used-as-indices-must-be-of-integer-or-boolean-type/

**Comment by cunhasdepedra** [comment]
\anaconda3\lib\site-packages\pandas\core\arrays\_mixins.py in __getitem__(self, key)
    227         key = extract_array(key, extract_numpy=True)
    228         key = check_array_indexer(self, key)
--> 229         result = self._ndarray[key]
    230         if lib.is_scalar(result):
    231             return self._box_func(result)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by djoffrey** [comment]
I still don't get your problem
could you paste the result that ```print(klines[0])``` output?
As I recall the ccxt fetch_kline should looks like this: ```columns=['ts', 'open', 'high', 'low', 'close', 'volume' ]```

**Comment by djoffrey** [comment]
Should be easy to address the problem, you should check what ccxt returns, and convert them to pd.DataFrame

**Comment by cunhasdepedra** [comment]
I'm not using ccxxt, I'm calculating directly from binance futures historical data. I'm very close to getting this solved just by trial and error. But you already helped me.

**Comment by cunhasdepedra** [comment]
Those are the final lines of my code: 

> def fetch_historical_data(symbol, interval, min_required=500, start_time=None, end_time=None):
    try:
        klines = client.get_klines(symbol=symbol, interval=interval, limit=min_required, startTime=start_time, endTime=end_time)
        data = pd.DataFrame(klines, columns=["open_time", "open", "high", "low", "close", "volume", "close_time", "quote_asset_volume", "number_of_trades", "taker_buy_base_asset_volume", "taker_buy_quote_asset_volume", "ignore"])
        data = data.astype({"open": "float64", "high": "float64", "low": "float64", "close": "float64"})
        
        if data.shape[0] < min_required:
            klines = client.get_klines(symbol=symbol, interval=interval, startTime=start_time, endTime=end_time)
            data = pd.DataFrame(klines, columns=["open_time", "open", "high", "low", "close", "volume", "close_time", "quote_asset_volume", "number_of_trades", "taker_buy_base_asset_volume", "taker_buy_quote_asset_volume", "ignore"])
            data = data.astype({"open": "float64", "high": "float64", "low": "float64", "close": "float64"})

        # Convert 'open_time' to datetime and set it as the index
        data['open_time'] = pd.to_datetime(data['open_time'], unit='ms')
        data.set_index('open_time', inplace=True)
        
        return data

    except BinanceAPIException as e:
        print(f"Error fetching historical data for {symbol}: {e}")
        return pd.DataFrame()

    
def analyze_patterns(interval):
    usdt_pairs = fetch_usdt_pairs()

    bullish_patterns = []
    bearish_patterns = []

    for symbol in usdt_pairs:
        data = fetch_historical_data(symbol, interval)
        if not data.empty:
            harmonic_detector = HarmonicDetector()
            patterns, _ = harmonic_detector.search_patterns(data)  # Extract only the found patterns list
            if len(patterns) > 0:
                latest_pattern = patterns[-1]
                if "bullish" in latest_pattern[2]:
                    bullish_patterns.append((symbol, latest_pattern, data))
                elif "bearish" in latest_pattern[2]:
                    bearish_patterns.append((symbol, latest_pattern, data))
        else:
            print(f"Symbol: {symbol}")
            print("No data available\n")

        time.sleep(1)  # Add sleep to avoid hitting rate limits

    # Print the patterns
    for pattern in bullish_patterns + bearish_patterns:
        print(f"Symbol: {pattern[0]}")
        print(f"Pattern: {pattern[1][2]}")
        print("Prices:", [point[1] for point in pattern[1][0]])
        print("Timestamps:", [pattern[2].index[point[0]] for point in pattern[1][1]])
        print("\n")


if __name__ == "__main__":
    intervals = [
        Client.KLINE_INTERVAL_2HOUR,
        Client.KLINE_INTERVAL_4HOUR,
        Client.KLINE_INTERVAL_12HOUR,
        Client.KLINE_INTERVAL_1DAY,
        Client.KLINE_INTERVAL_3DAY,
    ]

    for interval in intervals:
        analyze_patterns(interval)

**Comment by djoffrey** [comment]
ok, I took a short nap, did you solved it ? The sugguestion is to check the ccxt fect_kline in Binance api,

I use the ccxt library, but it fetch kline from binance api too, and it is opensource

**Comment by cunhasdepedra** [comment]
I didnt solve it. Me and gpt4 are too dumb for it it seems.

**Comment by djoffrey** [comment]
> I didnt solve it. Me and gpt4 are too dumb for it it seems.

At least you got gpt4 to help you, haha

**Comment by cunhasdepedra** [comment]
@djoffrey can I send you the entire code somewhere? Im pretty sure u can solve this in 15min, and you'll get good alpha for free.

**Comment by djoffrey** [comment]
You don't need to send me the entire code, I am pretty sure you just need to handle the pandas DataFrame to solve your problem.

Could you try ccxt at first?

**Comment by cunhasdepedra** [comment]
Trying ccxt will mean redoing the entire code... and ccxxt brings other problems, I cant make my binance API work with it. I just dont know why, but I cant. Really sorry to bother.

**Comment by cunhasdepedra** [comment]
I invited you: 

https://github.com/cunhasdepedra/harmonicpatterns

**Comment by djoffrey** [comment]
Okay~

**Comment by djoffrey** [comment]
@cunhasdepedra 
```python
def fetch_historical_data(symbol, interval, start_time=None, end_time=None):
    try:
        klines = client.get_klines(symbol=symbol, interval=interval, startTime=start_time, endTime=end_time)
        data = pd.DataFrame(klines, columns=["open_time", "open", "high", "low", "close", "volume", "close_time", "quote_asset_volume", "number_of_trades", "taker_buy_base_asset_volume", "taker_buy_quote_asset_volume", "ignore"])
        data = data.astype({"open_time": "int64", "open": "float64", "high": "float64", "low": "float64", "close": "float64"})
        data.index = pd.to_datetime(data.open_time, unit='ms')
        del data['open_time']
        return data
    except BinanceAPIException as e:
        print(f"Error fetching historical data for {symbol}: {e}")
        return pd.DataFrame()

```

**Comment by cunhasdepedra** [comment]
Lol, that was elegant. Thanks man. I'm still having some problems but they're different. Can I keep in touch?

**Comment by djoffrey** [comment]
> Lol, that was elegant. Thanks man. I'm still having some problems but they're different. Can I keep in touch?

You could paste more detailed messages to here, if I can solve it, I'll take some time help you.

**Comment by cunhasdepedra** [comment]
Well it looks like now I'm not having problems with timestamps anymore, but now I can't find a single pattern in my search. The problem is that the code is too long and I don't know if the cells are communicating rightly with each other to do what's intented. The new code is on the repository. 

https://github.com/cunhasdepedra/harmonicpatterns

**Comment by cunhasdepedra** [comment]
I made an advancement, I was calling for the search patterns function, but the get pattern seems more likely to give me past patterns.

**Comment by djoffrey** [comment]
> I made an advancement, I was calling for the search patterns function, but the get pattern seems more likely to give me past patterns.

I see. 
If u need only newest result of kline, u should set ```only_last=True``` to search_patterns, check this:

```python
                patterns, predicted_patterns = harmonic_detector.search_patterns(data, return_dt_idx=True, only_last=True)
```

But if there is no result, the return value is None

**Comment by cunhasdepedra** [comment]
I want: 

- The five timestamps (five points that made a pattern) (normal date, not UNIX)
- The five prices
- The type of pattern
- The timeframe

And somehow I can't get to that. Can you take a look at the repo I shared with you?

**Comment by djoffrey** [comment]
Those data are all included in the return val.

But It is a bit trivial, I suggest you take a look a the code, anyway it is quite short(except the pattern matching part).

**Comment by cunhasdepedra** [comment]
If its trivial why cant you help me? Im dumb.

**Comment by djoffrey** [comment]
LOL, I think you are able to fix it, I saw your code. These are some small problems, believe in yourself, best wishes.

**Comment by cunhasdepedra** [comment]
Ive been stumbling upon this error quite often: 

AttributeError                            Traceback (most recent call last)
<ipython-input-1-28ce96fd05a6> in <module>
   1580 
   1581     for interval in intervals:
-> 1582         analyze_patterns(interval)

<ipython-input-1-28ce96fd05a6> in analyze_patterns(interval)
   1536             else:
   1537                 window = 10  # Adjust the window size as needed
-> 1538                 patterns, _, timeframe = harmonic_detector.get_patterns(data, window, interval, predict=True)
   1539                 if len(patterns) > 0:
   1540                     latest_pattern = patterns[-1]

AttributeError: 'HarmonicDetector' object has no attribute 'get_patterns'

How do i deal with it?

**Comment by cunhasdepedra** [comment]
I managed an alternative solution. All is well. Thanks!!
